//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace PowerScada.Rapor.Form23 {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("Form23OlenlerinYasDagilimiDataSet")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class Form23OlenlerinYasDagilimiDataSet : global::System.Data.DataSet {
        
        private OlenlerinYasDagilimiDataTableDataTable tableOlenlerinYasDagilimiDataTable;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public Form23OlenlerinYasDagilimiDataSet() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected Form23OlenlerinYasDagilimiDataSet(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["OlenlerinYasDagilimiDataTable"] != null)) {
                    base.Tables.Add(new OlenlerinYasDagilimiDataTableDataTable(ds.Tables["OlenlerinYasDagilimiDataTable"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public OlenlerinYasDagilimiDataTableDataTable OlenlerinYasDagilimiDataTable {
            get {
                return this.tableOlenlerinYasDagilimiDataTable;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            Form23OlenlerinYasDagilimiDataSet cln = ((Form23OlenlerinYasDagilimiDataSet)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["OlenlerinYasDagilimiDataTable"] != null)) {
                    base.Tables.Add(new OlenlerinYasDagilimiDataTableDataTable(ds.Tables["OlenlerinYasDagilimiDataTable"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tableOlenlerinYasDagilimiDataTable = ((OlenlerinYasDagilimiDataTableDataTable)(base.Tables["OlenlerinYasDagilimiDataTable"]));
            if ((initTable == true)) {
                if ((this.tableOlenlerinYasDagilimiDataTable != null)) {
                    this.tableOlenlerinYasDagilimiDataTable.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void InitClass() {
            this.DataSetName = "Form23OlenlerinYasDagilimiDataSet";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/Form23OlenlerinYasDagilimiDataSet.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableOlenlerinYasDagilimiDataTable = new OlenlerinYasDagilimiDataTableDataTable();
            base.Tables.Add(this.tableOlenlerinYasDagilimiDataTable);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private bool ShouldSerializeOlenlerinYasDagilimiDataTable() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            Form23OlenlerinYasDagilimiDataSet ds = new Form23OlenlerinYasDagilimiDataSet();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public delegate void OlenlerinYasDagilimiDataTableRowChangeEventHandler(object sender, OlenlerinYasDagilimiDataTableRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class OlenlerinYasDagilimiDataTableDataTable : global::System.Data.TypedTableBase<OlenlerinYasDagilimiDataTableRow> {
            
            private global::System.Data.DataColumn columnSifirYediGun;
            
            private global::System.Data.DataColumn columnBirDortGun;
            
            private global::System.Data.DataColumn columnYirmidokuzUcYuzAltmisDort;
            
            private global::System.Data.DataColumn columnBirDortYil;
            
            private global::System.Data.DataColumn columnBesDokuzYil;
            
            private global::System.Data.DataColumn columnOnOnDortYil;
            
            private global::System.Data.DataColumn columnOnBesYirmiDortYil;
            
            private global::System.Data.DataColumn columnYirmiBesKirkDortYil;
            
            private global::System.Data.DataColumn columnKirkBesKirkDokuzYil;
            
            private global::System.Data.DataColumn columnElliAltmisDortYil;
            
            private global::System.Data.DataColumn columnAltmisBesUstu;
            
            private global::System.Data.DataColumn columnCinsiyeti;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public OlenlerinYasDagilimiDataTableDataTable() {
                this.TableName = "OlenlerinYasDagilimiDataTable";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal OlenlerinYasDagilimiDataTableDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected OlenlerinYasDagilimiDataTableDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn SifirYediGunColumn {
                get {
                    return this.columnSifirYediGun;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn BirDortGunColumn {
                get {
                    return this.columnBirDortGun;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn YirmidokuzUcYuzAltmisDortColumn {
                get {
                    return this.columnYirmidokuzUcYuzAltmisDort;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn BirDortYilColumn {
                get {
                    return this.columnBirDortYil;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn BesDokuzYilColumn {
                get {
                    return this.columnBesDokuzYil;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn OnOnDortYilColumn {
                get {
                    return this.columnOnOnDortYil;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn OnBesYirmiDortYilColumn {
                get {
                    return this.columnOnBesYirmiDortYil;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn YirmiBesKirkDortYilColumn {
                get {
                    return this.columnYirmiBesKirkDortYil;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn KirkBesKirkDokuzYilColumn {
                get {
                    return this.columnKirkBesKirkDokuzYil;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn ElliAltmisDortYilColumn {
                get {
                    return this.columnElliAltmisDortYil;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn AltmisBesUstuColumn {
                get {
                    return this.columnAltmisBesUstu;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn CinsiyetiColumn {
                get {
                    return this.columnCinsiyeti;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public OlenlerinYasDagilimiDataTableRow this[int index] {
                get {
                    return ((OlenlerinYasDagilimiDataTableRow)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event OlenlerinYasDagilimiDataTableRowChangeEventHandler OlenlerinYasDagilimiDataTableRowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event OlenlerinYasDagilimiDataTableRowChangeEventHandler OlenlerinYasDagilimiDataTableRowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event OlenlerinYasDagilimiDataTableRowChangeEventHandler OlenlerinYasDagilimiDataTableRowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event OlenlerinYasDagilimiDataTableRowChangeEventHandler OlenlerinYasDagilimiDataTableRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void AddOlenlerinYasDagilimiDataTableRow(OlenlerinYasDagilimiDataTableRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public OlenlerinYasDagilimiDataTableRow AddOlenlerinYasDagilimiDataTableRow(string SifirYediGun, string BirDortGun, string YirmidokuzUcYuzAltmisDort, string BirDortYil, string BesDokuzYil, string OnOnDortYil, string OnBesYirmiDortYil, string YirmiBesKirkDortYil, string KirkBesKirkDokuzYil, string ElliAltmisDortYil, string AltmisBesUstu, string Cinsiyeti) {
                OlenlerinYasDagilimiDataTableRow rowOlenlerinYasDagilimiDataTableRow = ((OlenlerinYasDagilimiDataTableRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        SifirYediGun,
                        BirDortGun,
                        YirmidokuzUcYuzAltmisDort,
                        BirDortYil,
                        BesDokuzYil,
                        OnOnDortYil,
                        OnBesYirmiDortYil,
                        YirmiBesKirkDortYil,
                        KirkBesKirkDokuzYil,
                        ElliAltmisDortYil,
                        AltmisBesUstu,
                        Cinsiyeti};
                rowOlenlerinYasDagilimiDataTableRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowOlenlerinYasDagilimiDataTableRow);
                return rowOlenlerinYasDagilimiDataTableRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                OlenlerinYasDagilimiDataTableDataTable cln = ((OlenlerinYasDagilimiDataTableDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new OlenlerinYasDagilimiDataTableDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal void InitVars() {
                this.columnSifirYediGun = base.Columns["SifirYediGun"];
                this.columnBirDortGun = base.Columns["BirDortGun"];
                this.columnYirmidokuzUcYuzAltmisDort = base.Columns["YirmidokuzUcYuzAltmisDort"];
                this.columnBirDortYil = base.Columns["BirDortYil"];
                this.columnBesDokuzYil = base.Columns["BesDokuzYil"];
                this.columnOnOnDortYil = base.Columns["OnOnDortYil"];
                this.columnOnBesYirmiDortYil = base.Columns["OnBesYirmiDortYil"];
                this.columnYirmiBesKirkDortYil = base.Columns["YirmiBesKirkDortYil"];
                this.columnKirkBesKirkDokuzYil = base.Columns["KirkBesKirkDokuzYil"];
                this.columnElliAltmisDortYil = base.Columns["ElliAltmisDortYil"];
                this.columnAltmisBesUstu = base.Columns["AltmisBesUstu"];
                this.columnCinsiyeti = base.Columns["Cinsiyeti"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            private void InitClass() {
                this.columnSifirYediGun = new global::System.Data.DataColumn("SifirYediGun", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSifirYediGun);
                this.columnBirDortGun = new global::System.Data.DataColumn("BirDortGun", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnBirDortGun);
                this.columnYirmidokuzUcYuzAltmisDort = new global::System.Data.DataColumn("YirmidokuzUcYuzAltmisDort", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnYirmidokuzUcYuzAltmisDort);
                this.columnBirDortYil = new global::System.Data.DataColumn("BirDortYil", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnBirDortYil);
                this.columnBesDokuzYil = new global::System.Data.DataColumn("BesDokuzYil", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnBesDokuzYil);
                this.columnOnOnDortYil = new global::System.Data.DataColumn("OnOnDortYil", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnOnOnDortYil);
                this.columnOnBesYirmiDortYil = new global::System.Data.DataColumn("OnBesYirmiDortYil", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnOnBesYirmiDortYil);
                this.columnYirmiBesKirkDortYil = new global::System.Data.DataColumn("YirmiBesKirkDortYil", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnYirmiBesKirkDortYil);
                this.columnKirkBesKirkDokuzYil = new global::System.Data.DataColumn("KirkBesKirkDokuzYil", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnKirkBesKirkDokuzYil);
                this.columnElliAltmisDortYil = new global::System.Data.DataColumn("ElliAltmisDortYil", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnElliAltmisDortYil);
                this.columnAltmisBesUstu = new global::System.Data.DataColumn("AltmisBesUstu", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnAltmisBesUstu);
                this.columnCinsiyeti = new global::System.Data.DataColumn("Cinsiyeti", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCinsiyeti);
                this.columnSifirYediGun.Caption = "DataColumn1";
                this.columnBirDortGun.Caption = "DataColumn2";
                this.columnYirmidokuzUcYuzAltmisDort.Caption = "DataColumn1";
                this.columnBirDortYil.Caption = "DataColumn2";
                this.columnOnOnDortYil.Caption = "DataColumn1";
                this.columnOnBesYirmiDortYil.Caption = "DataColumn2";
                this.columnKirkBesKirkDokuzYil.Caption = "DataColumn1";
                this.columnElliAltmisDortYil.Caption = "DataColumn2";
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public OlenlerinYasDagilimiDataTableRow NewOlenlerinYasDagilimiDataTableRow() {
                return ((OlenlerinYasDagilimiDataTableRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new OlenlerinYasDagilimiDataTableRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(OlenlerinYasDagilimiDataTableRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.OlenlerinYasDagilimiDataTableRowChanged != null)) {
                    this.OlenlerinYasDagilimiDataTableRowChanged(this, new OlenlerinYasDagilimiDataTableRowChangeEvent(((OlenlerinYasDagilimiDataTableRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.OlenlerinYasDagilimiDataTableRowChanging != null)) {
                    this.OlenlerinYasDagilimiDataTableRowChanging(this, new OlenlerinYasDagilimiDataTableRowChangeEvent(((OlenlerinYasDagilimiDataTableRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.OlenlerinYasDagilimiDataTableRowDeleted != null)) {
                    this.OlenlerinYasDagilimiDataTableRowDeleted(this, new OlenlerinYasDagilimiDataTableRowChangeEvent(((OlenlerinYasDagilimiDataTableRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.OlenlerinYasDagilimiDataTableRowDeleting != null)) {
                    this.OlenlerinYasDagilimiDataTableRowDeleting(this, new OlenlerinYasDagilimiDataTableRowChangeEvent(((OlenlerinYasDagilimiDataTableRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void RemoveOlenlerinYasDagilimiDataTableRow(OlenlerinYasDagilimiDataTableRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                Form23OlenlerinYasDagilimiDataSet ds = new Form23OlenlerinYasDagilimiDataSet();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "OlenlerinYasDagilimiDataTableDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class OlenlerinYasDagilimiDataTableRow : global::System.Data.DataRow {
            
            private OlenlerinYasDagilimiDataTableDataTable tableOlenlerinYasDagilimiDataTable;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal OlenlerinYasDagilimiDataTableRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableOlenlerinYasDagilimiDataTable = ((OlenlerinYasDagilimiDataTableDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string SifirYediGun {
                get {
                    try {
                        return ((string)(this[this.tableOlenlerinYasDagilimiDataTable.SifirYediGunColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'SifirYediGun\' in table \'OlenlerinYasDagilimiDataTable\' is D" +
                                "BNull.", e);
                    }
                }
                set {
                    this[this.tableOlenlerinYasDagilimiDataTable.SifirYediGunColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string BirDortGun {
                get {
                    try {
                        return ((string)(this[this.tableOlenlerinYasDagilimiDataTable.BirDortGunColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'BirDortGun\' in table \'OlenlerinYasDagilimiDataTable\' is DBN" +
                                "ull.", e);
                    }
                }
                set {
                    this[this.tableOlenlerinYasDagilimiDataTable.BirDortGunColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string YirmidokuzUcYuzAltmisDort {
                get {
                    try {
                        return ((string)(this[this.tableOlenlerinYasDagilimiDataTable.YirmidokuzUcYuzAltmisDortColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'YirmidokuzUcYuzAltmisDort\' in table \'OlenlerinYasDagilimiDa" +
                                "taTable\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableOlenlerinYasDagilimiDataTable.YirmidokuzUcYuzAltmisDortColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string BirDortYil {
                get {
                    try {
                        return ((string)(this[this.tableOlenlerinYasDagilimiDataTable.BirDortYilColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'BirDortYil\' in table \'OlenlerinYasDagilimiDataTable\' is DBN" +
                                "ull.", e);
                    }
                }
                set {
                    this[this.tableOlenlerinYasDagilimiDataTable.BirDortYilColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string BesDokuzYil {
                get {
                    try {
                        return ((string)(this[this.tableOlenlerinYasDagilimiDataTable.BesDokuzYilColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'BesDokuzYil\' in table \'OlenlerinYasDagilimiDataTable\' is DB" +
                                "Null.", e);
                    }
                }
                set {
                    this[this.tableOlenlerinYasDagilimiDataTable.BesDokuzYilColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string OnOnDortYil {
                get {
                    try {
                        return ((string)(this[this.tableOlenlerinYasDagilimiDataTable.OnOnDortYilColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'OnOnDortYil\' in table \'OlenlerinYasDagilimiDataTable\' is DB" +
                                "Null.", e);
                    }
                }
                set {
                    this[this.tableOlenlerinYasDagilimiDataTable.OnOnDortYilColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string OnBesYirmiDortYil {
                get {
                    try {
                        return ((string)(this[this.tableOlenlerinYasDagilimiDataTable.OnBesYirmiDortYilColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'OnBesYirmiDortYil\' in table \'OlenlerinYasDagilimiDataTable\'" +
                                " is DBNull.", e);
                    }
                }
                set {
                    this[this.tableOlenlerinYasDagilimiDataTable.OnBesYirmiDortYilColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string YirmiBesKirkDortYil {
                get {
                    try {
                        return ((string)(this[this.tableOlenlerinYasDagilimiDataTable.YirmiBesKirkDortYilColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'YirmiBesKirkDortYil\' in table \'OlenlerinYasDagilimiDataTabl" +
                                "e\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableOlenlerinYasDagilimiDataTable.YirmiBesKirkDortYilColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string KirkBesKirkDokuzYil {
                get {
                    try {
                        return ((string)(this[this.tableOlenlerinYasDagilimiDataTable.KirkBesKirkDokuzYilColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'KirkBesKirkDokuzYil\' in table \'OlenlerinYasDagilimiDataTabl" +
                                "e\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableOlenlerinYasDagilimiDataTable.KirkBesKirkDokuzYilColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string ElliAltmisDortYil {
                get {
                    try {
                        return ((string)(this[this.tableOlenlerinYasDagilimiDataTable.ElliAltmisDortYilColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ElliAltmisDortYil\' in table \'OlenlerinYasDagilimiDataTable\'" +
                                " is DBNull.", e);
                    }
                }
                set {
                    this[this.tableOlenlerinYasDagilimiDataTable.ElliAltmisDortYilColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string AltmisBesUstu {
                get {
                    try {
                        return ((string)(this[this.tableOlenlerinYasDagilimiDataTable.AltmisBesUstuColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'AltmisBesUstu\' in table \'OlenlerinYasDagilimiDataTable\' is " +
                                "DBNull.", e);
                    }
                }
                set {
                    this[this.tableOlenlerinYasDagilimiDataTable.AltmisBesUstuColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Cinsiyeti {
                get {
                    try {
                        return ((string)(this[this.tableOlenlerinYasDagilimiDataTable.CinsiyetiColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Cinsiyeti\' in table \'OlenlerinYasDagilimiDataTable\' is DBNu" +
                                "ll.", e);
                    }
                }
                set {
                    this[this.tableOlenlerinYasDagilimiDataTable.CinsiyetiColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsSifirYediGunNull() {
                return this.IsNull(this.tableOlenlerinYasDagilimiDataTable.SifirYediGunColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetSifirYediGunNull() {
                this[this.tableOlenlerinYasDagilimiDataTable.SifirYediGunColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsBirDortGunNull() {
                return this.IsNull(this.tableOlenlerinYasDagilimiDataTable.BirDortGunColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetBirDortGunNull() {
                this[this.tableOlenlerinYasDagilimiDataTable.BirDortGunColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsYirmidokuzUcYuzAltmisDortNull() {
                return this.IsNull(this.tableOlenlerinYasDagilimiDataTable.YirmidokuzUcYuzAltmisDortColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetYirmidokuzUcYuzAltmisDortNull() {
                this[this.tableOlenlerinYasDagilimiDataTable.YirmidokuzUcYuzAltmisDortColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsBirDortYilNull() {
                return this.IsNull(this.tableOlenlerinYasDagilimiDataTable.BirDortYilColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetBirDortYilNull() {
                this[this.tableOlenlerinYasDagilimiDataTable.BirDortYilColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsBesDokuzYilNull() {
                return this.IsNull(this.tableOlenlerinYasDagilimiDataTable.BesDokuzYilColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetBesDokuzYilNull() {
                this[this.tableOlenlerinYasDagilimiDataTable.BesDokuzYilColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsOnOnDortYilNull() {
                return this.IsNull(this.tableOlenlerinYasDagilimiDataTable.OnOnDortYilColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetOnOnDortYilNull() {
                this[this.tableOlenlerinYasDagilimiDataTable.OnOnDortYilColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsOnBesYirmiDortYilNull() {
                return this.IsNull(this.tableOlenlerinYasDagilimiDataTable.OnBesYirmiDortYilColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetOnBesYirmiDortYilNull() {
                this[this.tableOlenlerinYasDagilimiDataTable.OnBesYirmiDortYilColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsYirmiBesKirkDortYilNull() {
                return this.IsNull(this.tableOlenlerinYasDagilimiDataTable.YirmiBesKirkDortYilColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetYirmiBesKirkDortYilNull() {
                this[this.tableOlenlerinYasDagilimiDataTable.YirmiBesKirkDortYilColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsKirkBesKirkDokuzYilNull() {
                return this.IsNull(this.tableOlenlerinYasDagilimiDataTable.KirkBesKirkDokuzYilColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetKirkBesKirkDokuzYilNull() {
                this[this.tableOlenlerinYasDagilimiDataTable.KirkBesKirkDokuzYilColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsElliAltmisDortYilNull() {
                return this.IsNull(this.tableOlenlerinYasDagilimiDataTable.ElliAltmisDortYilColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetElliAltmisDortYilNull() {
                this[this.tableOlenlerinYasDagilimiDataTable.ElliAltmisDortYilColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsAltmisBesUstuNull() {
                return this.IsNull(this.tableOlenlerinYasDagilimiDataTable.AltmisBesUstuColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetAltmisBesUstuNull() {
                this[this.tableOlenlerinYasDagilimiDataTable.AltmisBesUstuColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsCinsiyetiNull() {
                return this.IsNull(this.tableOlenlerinYasDagilimiDataTable.CinsiyetiColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetCinsiyetiNull() {
                this[this.tableOlenlerinYasDagilimiDataTable.CinsiyetiColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public class OlenlerinYasDagilimiDataTableRowChangeEvent : global::System.EventArgs {
            
            private OlenlerinYasDagilimiDataTableRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public OlenlerinYasDagilimiDataTableRowChangeEvent(OlenlerinYasDagilimiDataTableRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public OlenlerinYasDagilimiDataTableRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591